from app.models import db, Restaurant, environment, SCHEMA

# type [korean, japanese, american, chinese, fastfood, drinks]

restaurants = [
    {
        'owner_id': 1,
        'name': 'Kunjip',
        'address': '1006 Kiely Blvd',
        'city': 'Santa Clara',
        'state': 'CA',
        'country': 'USA',
        'zipcode': '95051',
        'price': '$$',
        'phone_number': '408-246-0025',
        'preview_image': 'https://s3-media0.fl.yelpcdn.com/bphoto/lgK3XsiykZ6MhOSCH6Jsog/348s.jpg',
        'start_hours': ['10:00 AM'],
        'end_hours': ['9:00 PM'],
    },
    {
        'owner_id': 2,
        'name': 'Chungdam',
        'address': '3180 EL Camino Real',
        'city': 'Santa Clara',
        'state': 'CA',
        'country': 'USA',
        'zipcode': '95051',
        'price': '$$$',
        'phone_number': '669-306-4642',
        'preview_image': 'https://s3-media0.fl.yelpcdn.com/bphoto/939DUnel5bqTx1ttIyco2A/348s.jpg',
        'start_hours': ['11:30 AM', '5:00PM'],
        'end_hours': ['2:30 PM', '8:30 PM'],
    },
    {
        'owner_id': 3,
        'name': 'Daeho Kalbi Jjim & Beef Soup',
        'address': '217 W Calaveras Blvd',
        'city': 'Milpitas',
        'state': 'CA',
        'country': 'USA',
        'zipcode': '95035',
        'price': '$$$',
        'phone_number': '408-770-3778',
        'preview_image': 'https://s3-media0.fl.yelpcdn.com/bphoto/bbbaXkwRLl-BFEd3LNBC5A/348s.jpg',
        'start_hours': ['11:00 AM', '4:30 PM'],
        'end_hours': ['2:30 PM', '9:00 PM'],
    },
    {
        'owner_id': 4,
        'name': '10 Butchers Korean BBQ',
        'address': '595 E El Camino Real',
        'city': 'Sunnyvale',
        'state': 'CA',
        'country': 'USA',
        'zipcode': '94087',
        'price': '$$$$',
        'phone_number': '408-720-8889',
        'preview_image': 'https://s3-media0.fl.yelpcdn.com/bphoto/-4u6nWQ9rUUsAjsUBBP-sA/348s.jpg',
        'start_hours': ['11:30 AM', '5:00 PM'],
        'end_hours': ['2:30 PM', '9:00 PM'],
    },
    {
        'owner_id': 5,
        'name': 'Sumiya',
        'address': '2634 Homestead Rd',
        'city': 'Santa Clara',
        'state': 'CA',
        'country': 'USA',
        'zipcode': '95051',
        'price': '$$',
        'phone_number': '408-973-0604',
        'preview_image': 'https://s3-media0.fl.yelpcdn.com/bphoto/N-242Y3RF8sEfNBSErwImQ/348s.jpg',
        'start_hours': ['11:30AM', '5:30 PM'],
        'end_hours': ['1:30 PM', '9:00 PM'],
    },
    {
        'owner_id': 6,
        'name': 'Rantei Japanese Cuisine',
        'address': '1271 Franklin Mall',
        'city': 'Santa Clara',
        'state': 'CA',
        'country': 'USA',
        'zipcode': '95050',
        'price': '$$$',
        'phone_number': '408-352-5683',
        'preview_image': 'https://s3-media0.fl.yelpcdn.com/bphoto/EC7xvgMkhxmDCSSk4oXiFw/348s.jpg',
        'start_hours': ['4:30 PM'],
        'end_hours': ['9:00 PM'],
    },
    {
        'owner_id': 4,
        'name': 'Izakaya Restaurant',
        'address': '1335 N 1st St',
        'city': 'San Jose',
        'state': 'CA',
        'country': 'USA',
        'zipcode': '95112',
        'price': '$$',
        'phone_number': '408-452-8751',
        'preview_image': 'https://s3-media0.fl.yelpcdn.com/bphoto/KXh4HODT6W4DkbQ254QcCQ/348s.jpg',
        'start_hours': ['5:30 PM'],
        'end_hours': ['11:30 PM'],
    },
    {
        'owner_id': 3,
        'name': 'Amami Shima Sushi',
        'address': '19068 Stevens Creek Blvd',
        'city': 'Cupertino',
        'state': 'CA',
        'country': 'USA',
        'zipcode': '95014',
        'price': '$$',
        'phone_number': '408-996-8815',
        'preview_image': 'https://s3-media0.fl.yelpcdn.com/bphoto/pxcpMMFRhd9xqlo3s5aP4A/348s.jpg',
        'start_hours': ['4:30 PM'],
        'end_hours': ['9:00 PM'],
    },
    # {
    #     'owner_id': ,
    #     'name': '',
    #     'address': '',
    #     'city': '',
    #     'state': '',
    #     'country': '',
    #     'zipcode': '',
    #     'price': '',
    #     'phone_number': '',
    #     'preview_image': '',
    #     'start_hours': '',
    #     'end_hours': '',
    # },
    # {
    #     'owner_id': ,
    #     'name': '',
    #     'address': '',
    #     'city': '',
    #     'state': '',
    #     'country': '',
    #     'zipcode': '',
    #     'price': '',
    #     'phone_number': '',
    #     'preview_image': '',
    #     'start_hours': '',
    #     'end_hours': '',
    # },
]

def seed_restaurants():
    pass
def undo_restaurants():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.restaurants RESTART IDENTITY CASCADE;")
    else:
        db.session.execute("DELETE FROM restaurants")

    db.session.commit()
